server:
  port: 8054

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**
        - id : crew-service
          uri: lb://crew-service
          predicates:
            - Path=/crew/**
        - id : auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v1/**
        - id: trafic-service
          uri: lb://trafic-service
          predicates:
            - Path=/trafic/**
        - id: front-service
          uri: lb://front-service
          predicates:
            - Path=/UI/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
